
// Code generated by stanc v2.30.1
#include <stan/model/model_header.hpp>
namespace model_test_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 96> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 13, column 2 to column 27)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 14, column 2 to column 18)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 15, column 2 to column 17)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 17, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 17, column 2 to column 41)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 18, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 18, column 21 to column 32)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 18, column 2 to column 54)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 19, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 19, column 22 to column 33)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 19, column 2 to column 56)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 21, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 21, column 21 to column 32)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 21, column 2 to column 48)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 23, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 23, column 21 to column 32)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 23, column 41 to column 52)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 23, column 2 to column 65)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 24, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 24, column 21 to column 32)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 24, column 41 to column 52)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 24, column 2 to column 65)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 26, column 8 to column 19)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 26, column 21 to column 32)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 26, column 41 to column 51)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 26, column 53 to column 64)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 26, column 2 to column 75)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 28, column 9 to column 20)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 28, column 2 to column 24)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 29, column 9 to column 20)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 29, column 2 to column 25)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 30, column 9 to column 20)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 30, column 2 to column 28)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 35, column 10 to column 21)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 35, column 23 to column 34)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 35, column 43 to column 54)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 35, column 4 to column 68)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 36, column 10 to column 21)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 36, column 23 to column 34)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 36, column 43 to column 54)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 36, column 4 to column 69)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 40, column 12 to column 121)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 41, column 12 to column 122)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 39, column 31 to line 42, column 9)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 39, column 8 to line 42, column 9)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 38, column 29 to line 43, column 5)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 38, column 4 to line 43, column 5)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 45, column 10 to column 21)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 45, column 30 to column 40)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 45, column 4 to column 64)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 49, column 12 to line 59, column 30)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 48, column 31 to line 60, column 9)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 48, column 8 to line 60, column 9)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 47, column 29 to line 61, column 5)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 47, column 4 to line 61, column 5)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 63, column 4 to column 33)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 66, column 4 to column 16)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 67, column 4 to column 15)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 68, column 10 to column 21)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 68, column 30 to column 40)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 68, column 4 to column 68)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 72, column 12 to column 58)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 74, column 19 to column 31)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 74, column 12 to column 49)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 77, column 16 to line 84, column 18)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 76, column 37 to line 85, column 13)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 76, column 12 to line 85, column 13)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 86, column 12 to line 88, column 30)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 71, column 31 to line 89, column 9)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 71, column 8 to line 89, column 9)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 70, column 29 to line 90, column 5)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 70, column 4 to line 90, column 5)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 92, column 4 to column 37)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 3, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 4, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 5, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 2, column 61, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 13, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 19, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 11, column 58, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 27, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 29, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 25, column 56, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 37, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 39, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 35, column 78, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 48, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 46, column 73, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 57, column 2, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/cpl.stan', line 55, column 132, included from\n'/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 2, column 0)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 5, column 8 to column 26)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 6, column 8 to column 27)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 7, column 8 to column 30)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 8, column 8 to column 61)",
 " (in '/Users/chrobin/Documents/zusammen/zusammen/stan_models/model_test.stan', line 4, column 94 to line 9, column 5)"};

struct cpl_flux_integrand_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  operator()(const T0__& x, const T1__& xc, const std::vector<T2__>& theta,
             const std::vector<T3__>& x_r, const std::vector<int>& x_i,
             std::ostream* pstream__) const;
};
struct integral_flux_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            typename T4__, typename T5__, typename T6__,
            stan::require_all_t<stan::is_col_vector<T0__>,
                                stan::is_vt_not_complex<T0__>,
                                stan::is_col_vector<T1__>,
                                stan::is_vt_not_complex<T1__>,
                                stan::is_col_vector<T2__>,
                                stan::is_vt_not_complex<T2__>,
                                stan::is_col_vector<T3__>,
                                stan::is_vt_not_complex<T3__>,
                                stan::is_stan_scalar<T4__>,
                                stan::is_stan_scalar<T5__>,
                                stan::is_stan_scalar<T6__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
                       stan::base_type_t<T2__>, stan::base_type_t<T3__>, T4__,
                       stan::promote_args_t<T5__, T6__>>, -1, 1>
  operator()(const T0__& ebounds_lo, const T1__& ebounds_hi,
             const T2__& ebounds_add, const T3__& ebounds_half,
             const T4__& norm, const T5__& ec, const T6__& alpha,
             std::ostream* pstream__) const;
};
struct differential_flux_scalar_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  operator()(const T0__& energy, const T1__& xc,
             const std::vector<T2__>& theta, const std::vector<T3__>& x_r,
             const std::vector<int>& x_i, std::ostream* pstream__) const;
};
struct cpl_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_col_vector<T0__>,
                                stan::is_vt_not_complex<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>, -1, 1>
  operator()(const T0__& energy, const T1__& norm, const T2__& ec,
             const T3__& alpha, std::ostream* pstream__) const;
};
struct differential_flux_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_col_vector<T0__>,
                                stan::is_vt_not_complex<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>, -1, 1>
  operator()(const T0__& energy, const T1__& norm, const T2__& ec,
             const T3__& alpha, std::ostream* pstream__) const;
};
struct cpl_indi_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  operator()(const T0__& energy, const T1__& K, const T2__& alpha,
             const T3__& ec, std::ostream* pstream__) const;
};
struct ggrb_int_cpl_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  operator()(const T0__& alpha, const T1__& ec, const T2__& emin,
             const T3__& emax, std::ostream* pstream__) const;
};

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  ggrb_int_cpl(const T0__& alpha, const T1__& ec, const T2__& emin,
               const T3__& emax, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ i1 = DUMMY_VAR__;
      current_statement__ = 74;
      i1 = (stan::math::gamma_q((2 + alpha), (emin / ec)) *
             stan::math::tgamma((2 + alpha)));
      local_scalar_t__ i2 = DUMMY_VAR__;
      current_statement__ = 75;
      i2 = (stan::math::gamma_q((2 + alpha), (emax / ec)) *
             stan::math::tgamma((2 + alpha)));
      current_statement__ = 76;
      return (-stan::math::square(ec) * (i2 - i1));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>, -1, 1>
  cpl(const T0__& energy_arg__, const T1__& norm, const T2__& ec,
      const T3__& alpha, std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    const auto& energy = stan::math::to_ref(energy_arg__);
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ piv = DUMMY_VAR__;
      current_statement__ = 78;
      piv = 100.;
      current_statement__ = 79;
      return stan::math::elt_multiply(
               stan::math::multiply(norm,
                 stan::math::pow(stan::math::divide(energy, piv), alpha)),
               stan::math::exp(
                 stan::math::divide(stan::math::minus(energy), ec)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  cpl_indi(const T0__& energy, const T1__& K, const T2__& alpha,
           const T3__& ec, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ piv = DUMMY_VAR__;
      current_statement__ = 81;
      piv = 100.;
      current_statement__ = 82;
      return ((K * stan::math::pow((energy / piv), alpha)) *
               stan::math::exp((-energy / ec)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  cpl_flux_integrand(const T0__& x, const T1__& xc,
                     const std::vector<T2__>& theta,
                     const std::vector<T3__>& x_r,
                     const std::vector<int>& x_i, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ out = DUMMY_VAR__;
      current_statement__ = 84;
      out = (x *
              cpl_indi(x,
                stan::model::rvalue(theta, "theta",
                  stan::model::index_uni(1)),
                stan::model::rvalue(theta, "theta",
                  stan::model::index_uni(2)),
                stan::model::rvalue(theta, "theta",
                  stan::model::index_uni(3)), pstream__));
      current_statement__ = 85;
      return out;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>, -1, 1>
  differential_flux(const T0__& energy_arg__, const T1__& norm,
                    const T2__& ec, const T3__& alpha,
                    std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    const auto& energy = stan::math::to_ref(energy_arg__);
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      current_statement__ = 87;
      return cpl(energy, norm, ec, alpha, pstream__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>,
                              stan::is_stan_scalar<T6__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
                     stan::base_type_t<T2__>, stan::base_type_t<T3__>, T4__,
                     stan::promote_args_t<T5__, T6__>>, -1, 1>
  integral_flux(const T0__& ebounds_lo_arg__, const T1__& ebounds_hi_arg__,
                const T2__& ebounds_add_arg__,
                const T3__& ebounds_half_arg__, const T4__& norm,
                const T5__& ec, const T6__& alpha, std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<stan::base_type_t<T0__>,
                                 stan::base_type_t<T1__>,
                                 stan::base_type_t<T2__>,
                                 stan::base_type_t<T3__>, T4__,
                                 stan::promote_args_t<T5__, T6__>>;
    int current_statement__ = 0; 
    const auto& ebounds_lo = stan::math::to_ref(ebounds_lo_arg__);
    const auto& ebounds_hi = stan::math::to_ref(ebounds_hi_arg__);
    const auto& ebounds_add = stan::math::to_ref(ebounds_add_arg__);
    const auto& ebounds_half = stan::math::to_ref(ebounds_half_arg__);
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      current_statement__ = 89;
      return stan::math::elt_multiply(ebounds_add,
               stan::math::add(
                 stan::math::add(
                   differential_flux(ebounds_lo, norm, ec, alpha, pstream__),
                   stan::math::multiply(4,
                     differential_flux(ebounds_half, norm, ec,
                       alpha, pstream__))),
                 differential_flux(ebounds_hi, norm, ec, alpha, pstream__)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  differential_flux_scalar(const T0__& energy, const T1__& xc,
                           const std::vector<T2__>& theta,
                           const std::vector<T3__>& x_r,
                           const std::vector<int>& x_i,
                           std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ K = DUMMY_VAR__;
      current_statement__ = 91;
      K = stan::model::rvalue(theta, "theta", stan::model::index_uni(1));
      local_scalar_t__ ec = DUMMY_VAR__;
      current_statement__ = 92;
      ec = stan::model::rvalue(theta, "theta", stan::model::index_uni(2));
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 93;
      alpha = stan::model::rvalue(theta, "theta", stan::model::index_uni(3));
      current_statement__ = 94;
      return ((K * stan::math::pow((energy / 100.), alpha)) *
               stan::math::exp((-energy / ec)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cpl_flux_integrand_functor__::operator()(const T0__& x, const T1__& xc,
                                         const std::vector<T2__>& theta,
                                         const std::vector<T3__>& x_r,
                                         const std::vector<int>& x_i,
                                         std::ostream* pstream__)  const
{
  return cpl_flux_integrand(x, xc, theta, x_r, x_i, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>,
                              stan::is_stan_scalar<T6__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
                     stan::base_type_t<T2__>, stan::base_type_t<T3__>, T4__,
                     stan::promote_args_t<T5__, T6__>>, -1, 1>
integral_flux_functor__::operator()(const T0__& ebounds_lo,
                                    const T1__& ebounds_hi,
                                    const T2__& ebounds_add,
                                    const T3__& ebounds_half,
                                    const T4__& norm, const T5__& ec,
                                    const T6__& alpha,
                                    std::ostream* pstream__)  const
{
  return integral_flux(ebounds_lo, ebounds_hi, ebounds_add, ebounds_half,
           norm, ec, alpha, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
differential_flux_scalar_functor__::operator()(const T0__& energy,
                                               const T1__& xc,
                                               const std::vector<T2__>& theta,
                                               const std::vector<T3__>& x_r,
                                               const std::vector<int>& x_i,
                                               std::ostream* pstream__) 
const
{
  return differential_flux_scalar(energy, xc, theta, x_r, x_i, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>, -1, 1>
cpl_functor__::operator()(const T0__& energy, const T1__& norm,
                          const T2__& ec, const T3__& alpha,
                          std::ostream* pstream__)  const
{
  return cpl(energy, norm, ec, alpha, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__>, -1, 1>
differential_flux_functor__::operator()(const T0__& energy, const T1__& norm,
                                        const T2__& ec, const T3__& alpha,
                                        std::ostream* pstream__)  const
{
  return differential_flux(energy, norm, ec, alpha, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cpl_indi_functor__::operator()(const T0__& energy, const T1__& K,
                               const T2__& alpha, const T3__& ec,
                               std::ostream* pstream__)  const
{
  return cpl_indi(energy, K, alpha, ec, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
ggrb_int_cpl_functor__::operator()(const T0__& alpha, const T1__& ec,
                                   const T2__& emin, const T3__& emax,
                                   std::ostream* pstream__)  const
{
  return ggrb_int_cpl(alpha, ec, emin, emax, pstream__);
}

 class model_test_model final : public model_base_crtp<model_test_model> {

 private:
  int N_intervals;
  int max_n_echan;
  int max_n_chan;
  std::vector<int> N_dets;
  std::vector<std::vector<int>> N_chan;
  std::vector<std::vector<int>> N_echan;
  std::vector<std::vector<double>> exposure;
  std::vector<std::vector<Eigen::Matrix<double, -1, 1>>> ebounds_hi;
  std::vector<std::vector<Eigen::Matrix<double, -1, 1>>> ebounds_lo;
  std::vector<std::vector<Eigen::Matrix<double, -1, -1>>> response;
  Eigen::Matrix<double, -1, 1> K_data__;
  Eigen::Matrix<double, -1, 1> ec_data__;
  Eigen::Matrix<double, -1, 1> alpha_data__;
  std::vector<std::vector<Eigen::Matrix<double, -1, 1>>> ebounds_add;
  std::vector<std::vector<Eigen::Matrix<double, -1, 1>>> ebounds_half;
  std::vector<Eigen::Matrix<double, -1, 1>> expected_model_counts;
  std::vector<double> x_r;
  std::vector<int> x_i;
  std::vector<Eigen::Matrix<double, -1, 1>> expected_model_counts_int; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> K{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> ec{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> alpha{nullptr, 0};
 
 public:
  ~model_test_model() { }
  
  inline std::string model_name() const final { return "model_test_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.1", "stancflags = --include-paths=/Users/chrobin/Documents/zusammen/zusammen/stan_models"};
  }
  
  
  model_test_model(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model_test_model_namespace::model_test_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 1;
      context__.validate_dims("data initialization","N_intervals","int",
           std::vector<size_t>{});
      N_intervals = std::numeric_limits<int>::min();
      
      
      current_statement__ = 1;
      N_intervals = context__.vals_i("N_intervals")[(1 - 1)];
      current_statement__ = 1;
      stan::math::check_greater_or_equal(function__, "N_intervals",
                                            N_intervals, 1);
      current_statement__ = 2;
      context__.validate_dims("data initialization","max_n_echan","int",
           std::vector<size_t>{});
      max_n_echan = std::numeric_limits<int>::min();
      
      
      current_statement__ = 2;
      max_n_echan = context__.vals_i("max_n_echan")[(1 - 1)];
      current_statement__ = 3;
      context__.validate_dims("data initialization","max_n_chan","int",
           std::vector<size_t>{});
      max_n_chan = std::numeric_limits<int>::min();
      
      
      current_statement__ = 3;
      max_n_chan = context__.vals_i("max_n_chan")[(1 - 1)];
      current_statement__ = 4;
      stan::math::validate_non_negative_index("N_dets", "N_intervals",
                                              N_intervals);
      current_statement__ = 5;
      context__.validate_dims("data initialization","N_dets","int",
           std::vector<size_t>{static_cast<size_t>(N_intervals)});
      N_dets = 
        std::vector<int>(N_intervals, std::numeric_limits<int>::min());
      
      
      current_statement__ = 5;
      N_dets = context__.vals_i("N_dets");
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "N_dets", N_dets, 0);
      current_statement__ = 6;
      stan::math::validate_non_negative_index("N_chan", "N_intervals",
                                              N_intervals);
      current_statement__ = 7;
      stan::math::validate_non_negative_index("N_chan", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 8;
      context__.validate_dims("data initialization","N_chan","int",
           std::vector<size_t>{static_cast<size_t>(N_intervals),
            static_cast<size_t>(stan::math::max(N_dets))});
      N_chan = 
        std::vector<std::vector<int>>(N_intervals, 
          std::vector<int>(stan::math::max(N_dets), 
            std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> N_chan_flat__;
        current_statement__ = 8;
        N_chan_flat__ = context__.vals_i("N_chan");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= stan::math::max(N_dets); ++sym1__) {
          current_statement__ = 8;
          for (int sym2__ = 1; sym2__ <= N_intervals; ++sym2__) {
            current_statement__ = 8;
            stan::model::assign(N_chan, N_chan_flat__[(pos__ - 1)],
              "assigning variable N_chan", stan::model::index_uni(sym2__),
                                             stan::model::index_uni(sym1__));
            current_statement__ = 8;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "N_chan", N_chan, 0);
      current_statement__ = 9;
      stan::math::validate_non_negative_index("N_echan", "N_intervals",
                                              N_intervals);
      current_statement__ = 10;
      stan::math::validate_non_negative_index("N_echan", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 11;
      context__.validate_dims("data initialization","N_echan","int",
           std::vector<size_t>{static_cast<size_t>(N_intervals),
            static_cast<size_t>(stan::math::max(N_dets))});
      N_echan = 
        std::vector<std::vector<int>>(N_intervals, 
          std::vector<int>(stan::math::max(N_dets), 
            std::numeric_limits<int>::min()));
      
      
      {
        std::vector<int> N_echan_flat__;
        current_statement__ = 11;
        N_echan_flat__ = context__.vals_i("N_echan");
        current_statement__ = 11;
        pos__ = 1;
        current_statement__ = 11;
        for (int sym1__ = 1; sym1__ <= stan::math::max(N_dets); ++sym1__) {
          current_statement__ = 11;
          for (int sym2__ = 1; sym2__ <= N_intervals; ++sym2__) {
            current_statement__ = 11;
            stan::model::assign(N_echan, N_echan_flat__[(pos__ - 1)],
              "assigning variable N_echan", stan::model::index_uni(sym2__),
                                              stan::model::index_uni(sym1__));
            current_statement__ = 11;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "N_echan", N_echan, 0);
      current_statement__ = 12;
      stan::math::validate_non_negative_index("exposure", "N_intervals",
                                              N_intervals);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("exposure", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 14;
      context__.validate_dims("data initialization","exposure","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals),
            static_cast<size_t>(stan::math::max(N_dets))});
      exposure = 
        std::vector<std::vector<double>>(N_intervals, 
          std::vector<double>(stan::math::max(N_dets), 
            std::numeric_limits<double>::quiet_NaN()));
      
      
      {
        std::vector<local_scalar_t__> exposure_flat__;
        current_statement__ = 14;
        exposure_flat__ = context__.vals_r("exposure");
        current_statement__ = 14;
        pos__ = 1;
        current_statement__ = 14;
        for (int sym1__ = 1; sym1__ <= stan::math::max(N_dets); ++sym1__) {
          current_statement__ = 14;
          for (int sym2__ = 1; sym2__ <= N_intervals; ++sym2__) {
            current_statement__ = 14;
            stan::model::assign(exposure, exposure_flat__[(pos__ - 1)],
              "assigning variable exposure", stan::model::index_uni(sym2__),
                                               stan::model::index_uni(sym1__));
            current_statement__ = 14;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 15;
      stan::math::validate_non_negative_index("ebounds_hi", "N_intervals",
                                              N_intervals);
      current_statement__ = 16;
      stan::math::validate_non_negative_index("ebounds_hi", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 17;
      stan::math::validate_non_negative_index("ebounds_hi", "max_n_echan",
                                              max_n_echan);
      current_statement__ = 18;
      context__.validate_dims("data initialization","ebounds_hi","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals),
            static_cast<size_t>(stan::math::max(N_dets)),
            static_cast<size_t>(max_n_echan)});
      ebounds_hi = 
        std::vector<std::vector<Eigen::Matrix<double, -1, 1>>>(N_intervals, 
          std::vector<Eigen::Matrix<double, -1, 1>>(stan::math::max(N_dets), 
            Eigen::Matrix<double, -1, 1>::Constant(max_n_echan,
              std::numeric_limits<double>::quiet_NaN())));
      
      
      {
        std::vector<local_scalar_t__> ebounds_hi_flat__;
        current_statement__ = 18;
        ebounds_hi_flat__ = context__.vals_r("ebounds_hi");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= max_n_echan; ++sym1__) {
          current_statement__ = 18;
          for (int sym2__ = 1; sym2__ <= stan::math::max(N_dets); ++sym2__) {
            current_statement__ = 18;
            for (int sym3__ = 1; sym3__ <= N_intervals; ++sym3__) {
              current_statement__ = 18;
              stan::model::assign(ebounds_hi, ebounds_hi_flat__[(pos__ - 1)],
                "assigning variable ebounds_hi", stan::model::index_uni(sym3__),
                                                   stan::model::index_uni(sym2__),
                                                   stan::model::index_uni(sym1__));
              current_statement__ = 18;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("ebounds_lo", "N_intervals",
                                              N_intervals);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("ebounds_lo", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 21;
      stan::math::validate_non_negative_index("ebounds_lo", "max_n_echan",
                                              max_n_echan);
      current_statement__ = 22;
      context__.validate_dims("data initialization","ebounds_lo","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals),
            static_cast<size_t>(stan::math::max(N_dets)),
            static_cast<size_t>(max_n_echan)});
      ebounds_lo = 
        std::vector<std::vector<Eigen::Matrix<double, -1, 1>>>(N_intervals, 
          std::vector<Eigen::Matrix<double, -1, 1>>(stan::math::max(N_dets), 
            Eigen::Matrix<double, -1, 1>::Constant(max_n_echan,
              std::numeric_limits<double>::quiet_NaN())));
      
      
      {
        std::vector<local_scalar_t__> ebounds_lo_flat__;
        current_statement__ = 22;
        ebounds_lo_flat__ = context__.vals_r("ebounds_lo");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= max_n_echan; ++sym1__) {
          current_statement__ = 22;
          for (int sym2__ = 1; sym2__ <= stan::math::max(N_dets); ++sym2__) {
            current_statement__ = 22;
            for (int sym3__ = 1; sym3__ <= N_intervals; ++sym3__) {
              current_statement__ = 22;
              stan::model::assign(ebounds_lo, ebounds_lo_flat__[(pos__ - 1)],
                "assigning variable ebounds_lo", stan::model::index_uni(sym3__),
                                                   stan::model::index_uni(sym2__),
                                                   stan::model::index_uni(sym1__));
              current_statement__ = 22;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 23;
      stan::math::validate_non_negative_index("response", "N_intervals",
                                              N_intervals);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("response", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 25;
      stan::math::validate_non_negative_index("response", "max_n_chan",
                                              max_n_chan);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("response", "max_n_echan",
                                              max_n_echan);
      current_statement__ = 27;
      context__.validate_dims("data initialization","response","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals),
            static_cast<size_t>(stan::math::max(N_dets)),
            static_cast<size_t>(max_n_chan),
            static_cast<size_t>(max_n_echan)});
      response = 
        std::vector<std::vector<Eigen::Matrix<double, -1, -1>>>(N_intervals, 
          std::vector<Eigen::Matrix<double, -1, -1>>(stan::math::max(N_dets), 
            Eigen::Matrix<double, -1, -1>::Constant(max_n_chan, max_n_echan,
              std::numeric_limits<double>::quiet_NaN())));
      
      
      {
        std::vector<local_scalar_t__> response_flat__;
        current_statement__ = 27;
        response_flat__ = context__.vals_r("response");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= max_n_echan; ++sym1__) {
          current_statement__ = 27;
          for (int sym2__ = 1; sym2__ <= max_n_chan; ++sym2__) {
            current_statement__ = 27;
            for (int sym3__ = 1; sym3__ <= stan::math::max(N_dets); ++sym3__) {
              current_statement__ = 27;
              for (int sym4__ = 1; sym4__ <= N_intervals; ++sym4__) {
                current_statement__ = 27;
                stan::model::assign(response, response_flat__[(pos__ - 1)],
                  "assigning variable response", stan::model::index_uni(sym4__),
                                                   stan::model::index_uni(sym3__),
                                                   stan::model::index_uni(sym2__),
                                                   stan::model::index_uni(sym1__));
                current_statement__ = 27;
                pos__ = (pos__ + 1);
              }
            }
          }
        }
      }
      current_statement__ = 28;
      stan::math::validate_non_negative_index("K", "N_intervals", N_intervals);
      current_statement__ = 29;
      context__.validate_dims("data initialization","K","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals)});
      K_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N_intervals,
          std::numeric_limits<double>::quiet_NaN());
      new (&K) Eigen::Map<Eigen::Matrix<double, -1, 1>>(K_data__.data(), N_intervals);
        
      
      {
        std::vector<local_scalar_t__> K_flat__;
        current_statement__ = 29;
        K_flat__ = context__.vals_r("K");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= N_intervals; ++sym1__) {
          current_statement__ = 29;
          stan::model::assign(K, K_flat__[(pos__ - 1)],
            "assigning variable K", stan::model::index_uni(sym1__));
          current_statement__ = 29;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 30;
      stan::math::validate_non_negative_index("ec", "N_intervals",
                                              N_intervals);
      current_statement__ = 31;
      context__.validate_dims("data initialization","ec","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals)});
      ec_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N_intervals,
          std::numeric_limits<double>::quiet_NaN());
      new (&ec) Eigen::Map<Eigen::Matrix<double, -1, 1>>(ec_data__.data(), N_intervals);
        
      
      {
        std::vector<local_scalar_t__> ec_flat__;
        current_statement__ = 31;
        ec_flat__ = context__.vals_r("ec");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= N_intervals; ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(ec, ec_flat__[(pos__ - 1)],
            "assigning variable ec", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("alpha", "N_intervals",
                                              N_intervals);
      current_statement__ = 33;
      context__.validate_dims("data initialization","alpha","double",
           std::vector<size_t>{static_cast<size_t>(N_intervals)});
      alpha_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N_intervals,
          std::numeric_limits<double>::quiet_NaN());
      new (&alpha) Eigen::Map<Eigen::Matrix<double, -1, 1>>(alpha_data__.data(), N_intervals);
        
      
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 33;
        alpha_flat__ = context__.vals_r("alpha");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= N_intervals; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("ebounds_add", "N_intervals",
                                              N_intervals);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("ebounds_add", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 36;
      stan::math::validate_non_negative_index("ebounds_add", "max_n_echan",
                                              max_n_echan);
      current_statement__ = 37;
      ebounds_add = 
        std::vector<std::vector<Eigen::Matrix<double, -1, 1>>>(N_intervals, 
          std::vector<Eigen::Matrix<double, -1, 1>>(stan::math::max(N_dets), 
            Eigen::Matrix<double, -1, 1>::Constant(max_n_echan,
              std::numeric_limits<double>::quiet_NaN())));
      
      
      current_statement__ = 38;
      stan::math::validate_non_negative_index("ebounds_half", "N_intervals",
                                              N_intervals);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("ebounds_half", "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 40;
      stan::math::validate_non_negative_index("ebounds_half", "max_n_echan",
                                              max_n_echan);
      current_statement__ = 41;
      ebounds_half = 
        std::vector<std::vector<Eigen::Matrix<double, -1, 1>>>(N_intervals, 
          std::vector<Eigen::Matrix<double, -1, 1>>(stan::math::max(N_dets), 
            Eigen::Matrix<double, -1, 1>::Constant(max_n_echan,
              std::numeric_limits<double>::quiet_NaN())));
      
      
      current_statement__ = 47;
      for (int n = 1; n <= N_intervals; ++n) {
        current_statement__ = 45;
        for (int m = 1;
             m <= stan::model::rvalue(N_dets, "N_dets",
                    stan::model::index_uni(n));
             ++m) {
          current_statement__ = 42;
          stan::model::assign(ebounds_half,
            stan::math::multiply(0.5,
              stan::math::add(
                stan::model::rvalue(ebounds_hi, "ebounds_hi",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_min_max(1, stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m)))),
                stan::model::rvalue(ebounds_lo, "ebounds_lo",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_min_max(1, stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m)))))),
            "assigning variable ebounds_half", stan::model::index_uni(n),
                                                 stan::model::index_uni(m),
                                                 stan::model::index_min_max(1, 
                                                 stan::model::rvalue(N_echan,
                                                   "N_echan",
                                                   stan::model::index_uni(n),
                                                     stan::model::index_uni(m))));
          current_statement__ = 43;
          stan::model::assign(ebounds_add,
            stan::math::divide(
              stan::math::subtract(
                stan::model::rvalue(ebounds_hi, "ebounds_hi",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_min_max(1, stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m)))),
                stan::model::rvalue(ebounds_lo, "ebounds_lo",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_min_max(1, stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m))))),
              6.0),
            "assigning variable ebounds_add", stan::model::index_uni(n),
                                                stan::model::index_uni(m),
                                                stan::model::index_min_max(1, 
                                                stan::model::rvalue(N_echan,
                                                  "N_echan",
                                                  stan::model::index_uni(n),
                                                    stan::model::index_uni(m))));
        }
      }
      current_statement__ = 48;
      stan::math::validate_non_negative_index("expected_model_counts",
                                              "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 49;
      stan::math::validate_non_negative_index("expected_model_counts",
                                              "max_n_chan", max_n_chan);
      current_statement__ = 50;
      expected_model_counts = 
        std::vector<Eigen::Matrix<double, -1, 1>>(stan::math::max(N_dets), 
          Eigen::Matrix<double, -1, 1>::Constant(max_n_chan,
            std::numeric_limits<double>::quiet_NaN()));
      
      
      current_statement__ = 55;
      for (int n = 1; n <= N_intervals; ++n) {
        current_statement__ = 53;
        for (int m = 1;
             m <= stan::model::rvalue(N_dets, "N_dets",
                    stan::model::index_uni(n));
             ++m) {
          current_statement__ = 51;
          stan::model::assign(expected_model_counts,
            stan::math::multiply(
              stan::math::multiply(
                stan::model::rvalue(response, "response",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_min_max(1, stan::model::rvalue(N_chan,
                                                    "N_chan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m))),
                    stan::model::index_min_max(1, stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m)))),
                integral_flux(
                  stan::model::rvalue(ebounds_lo, "ebounds_lo",
                    stan::model::index_uni(n), stan::model::index_uni(m),
                      stan::model::index_min_max(1, stan::model::rvalue(
                                                      N_echan, "N_echan",
                                                      stan::model::index_uni(n),
                                                        stan::model::index_uni(m)))),
                  stan::model::rvalue(ebounds_hi, "ebounds_hi",
                    stan::model::index_uni(n), stan::model::index_uni(m),
                      stan::model::index_min_max(1, stan::model::rvalue(
                                                      N_echan, "N_echan",
                                                      stan::model::index_uni(n),
                                                        stan::model::index_uni(m)))),
                  stan::model::rvalue(ebounds_add, "ebounds_add",
                    stan::model::index_uni(n), stan::model::index_uni(m),
                      stan::model::index_min_max(1, stan::model::rvalue(
                                                      N_echan, "N_echan",
                                                      stan::model::index_uni(n),
                                                        stan::model::index_uni(m)))),
                  stan::model::rvalue(ebounds_half, "ebounds_half",
                    stan::model::index_uni(n), stan::model::index_uni(m),
                      stan::model::index_min_max(1, stan::model::rvalue(
                                                      N_echan, "N_echan",
                                                      stan::model::index_uni(n),
                                                        stan::model::index_uni(m)))),
                  stan::model::rvalue(K, "K", stan::model::index_uni(n)),
                  stan::model::rvalue(ec, "ec", stan::model::index_uni(n)),
                  stan::model::rvalue(alpha, "alpha",
                    stan::model::index_uni(n)), pstream__)),
              stan::model::rvalue(exposure, "exposure",
                stan::model::index_uni(n), stan::model::index_uni(m))),
            "assigning variable expected_model_counts", stan::model::index_uni(m),
                                                          stan::model::index_min_max(1, 
                                                          stan::model::rvalue(
                                                            N_chan, "N_chan",
                                                            stan::model::index_uni(n),
                                                              stan::model::index_uni(m))));
        }
      }
      current_statement__ = 56;
      if (pstream__) {
        stan::math::stan_print(pstream__, expected_model_counts);
        stan::math::stan_print(pstream__, "\n");
      }
      current_statement__ = 57;
      x_r = std::vector<double>(0, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 58;
      x_i = std::vector<int>(0, std::numeric_limits<int>::min());
      
      
      current_statement__ = 59;
      stan::math::validate_non_negative_index("expected_model_counts_int",
                                              "max(N_dets)",
                                              stan::math::max(N_dets));
      current_statement__ = 60;
      stan::math::validate_non_negative_index("expected_model_counts_int",
                                              "max_n_chan", max_n_chan);
      current_statement__ = 61;
      expected_model_counts_int = 
        std::vector<Eigen::Matrix<double, -1, 1>>(stan::math::max(N_dets), 
          Eigen::Matrix<double, -1, 1>::Constant(max_n_chan,
            std::numeric_limits<double>::quiet_NaN()));
      
      
      current_statement__ = 72;
      for (int n = 1; n <= N_intervals; ++n) {
        current_statement__ = 70;
        for (int m = 1;
             m <= stan::model::rvalue(N_dets, "N_dets",
                    stan::model::index_uni(n));
             ++m) {
          std::vector<double> theta =
             std::vector<double>(3, std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 62;
          stan::model::assign(theta, std::vector<double>{
            stan::model::rvalue(K, "K", stan::model::index_uni(n)),
            stan::model::rvalue(ec, "ec", stan::model::index_uni(n)),
            stan::model::rvalue(alpha, "alpha", stan::model::index_uni(n))},
            "assigning variable theta");
          current_statement__ = 63;
          stan::math::validate_non_negative_index("integrated_flux",
                                                  "N_echan[n, m]",
                                                  stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m)));
          Eigen::Matrix<double, -1, 1> integrated_flux =
             Eigen::Matrix<double, -1, 1>::Constant(
               stan::model::rvalue(N_echan, "N_echan",
                 stan::model::index_uni(n), stan::model::index_uni(m)),
               std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 67;
          for (int l = 1;
               l <= stan::model::rvalue(N_echan, "N_echan",
                      stan::model::index_uni(n), stan::model::index_uni(m));
               ++l) {
            current_statement__ = 65;
            stan::model::assign(integrated_flux,
              stan::math::integrate_1d(differential_flux_scalar_functor__(),
                stan::model::rvalue(ebounds_lo, "ebounds_lo",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_uni(l)),
                stan::model::rvalue(ebounds_hi, "ebounds_hi",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_uni(l)), theta, x_r, x_i, pstream__),
              "assigning variable integrated_flux", stan::model::index_uni(l));
          }
          current_statement__ = 68;
          stan::model::assign(expected_model_counts,
            stan::math::multiply(
              stan::math::multiply(
                stan::model::rvalue(response, "response",
                  stan::model::index_uni(n), stan::model::index_uni(m),
                    stan::model::index_min_max(1, stan::model::rvalue(N_chan,
                                                    "N_chan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m))),
                    stan::model::index_min_max(1, stan::model::rvalue(
                                                    N_echan, "N_echan",
                                                    stan::model::index_uni(n),
                                                      stan::model::index_uni(m)))),
                integrated_flux),
              stan::model::rvalue(exposure, "exposure",
                stan::model::index_uni(n), stan::model::index_uni(m))),
            "assigning variable expected_model_counts", stan::model::index_uni(m),
                                                          stan::model::index_min_max(1, 
                                                          stan::model::rvalue(
                                                            N_chan, "N_chan",
                                                            stan::model::index_uni(n),
                                                              stan::model::index_uni(m))));
        }
      }
      current_statement__ = 73;
      if (pstream__) {
        stan::math::stan_print(pstream__, expected_model_counts_int);
        stan::math::stan_print(pstream__, "\n");
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 0U;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_test_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_test_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 0> names__{};
      const std::array<Eigen::Index, 0> constrain_param_sizes__{};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } using stan_model = model_test_model_namespace::model_test_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model_test_model_namespace::profiles__;
}

#endif


